export const ICON_NAMES = Object.freeze({
  SUN: 'sun',
  MOON: 'moon',
  CHEVRON_RIGHT: 'chevron-right',
  GIT_BRANCH: 'git-branch',
  FILE_TREE_FOLDER: 'file-tree-folder',
  TEXT_BADGE: 'text-badge',
  FILE_DOCUMENT: 'file-document',
  FINDER_SIDEBAR_FOLDER: 'finder-sidebar-folder',
  FINDER_SIDEBAR_FOLDER_ACTIVE: 'finder-sidebar-folder-active',
  FINDER_SIDEBAR_TRASH: 'finder-sidebar-trash',
  APPLE_LOGO: 'apple-logo',
  WIFI: 'wifi',
  LANGUAGE: 'language',
  BATTERY: 'battery',
  DOCK_FINDER: 'dock-finder',
  DOCK_LAUNCHPAD: 'dock-launchpad',
  DOCK_NOTES: 'dock-notes',
  DOCK_SETTINGS: 'dock-settings',
  DOCK_TRASH: 'dock-trash',
  DOCK_OBSIDIAN: 'dock-obsidian',
})
